resource "aws_apigatewayv2_api" "apiv2"{
  count = var.gateway_version == 2 ? 1 : 0
  name          = var.api_gateway_name
  protocol_type = "HTTP"
}

resource "aws_api_gateway_rest_api" "apiv1" {
  count = var.gateway_version == 1 ? 1 : 0
  name          = var.api_gateway_name
  description = var.api_gateway_description
  endpoint_configuration {
    types = ["REGIONAL"]
  }
}

data "aws_lambda_function" "lambda_auth" {
  function_name = var.gateway_version == 1 ? "APIGatewayV1Authorizer" : "APIGatewayV2Authorizer"

}

data "aws_iam_role" "invocation_role" {
  name = "gateway_auth_invocation"
}

resource "aws_api_gateway_authorizer" "Token_Authorizer_V1" {
  count = var.gateway_version == 1 ? 1 : 0
  name                   = "APIV1TokenAuthorizer"
  rest_api_id            =  aws_api_gateway_rest_api.apiv1[count.index].id
  authorizer_uri         = data.aws_lambda_function.lambda_auth.invoke_arn
  authorizer_credentials = data.aws_iam_role.invocation_role.arn
#  identity_source                  = "method.request.header.Authorizer"
  //type = "TOKEN"
}

resource "aws_apigatewayv2_authorizer" "Token_Authorizer_V2" {
  count =  var.gateway_version == 2 ? 1 : 0
  api_id          = aws_apigatewayv2_api.apiv2[count.index].id
  authorizer_type = "REQUEST"
  name            = "APIV2TokenAuthorizer"
  authorizer_uri = data.aws_lambda_function.lambda_auth.invoke_arn
  authorizer_payload_format_version = "2.0"
}

// Api key who's value is generated by aws on creation
// TODO migrate all deployment to terraform cloud


# TODO needs to rotate


#data "aws_secretsmanager_secret" "version" {
#  count = var.authenticator_exists == false ? 1 : 0
#  name = "AuthenticatorGateway"
#}